{{- define "k8s-as-helm-lib.rolebinding.roleref.tpl" -}}
roleRef:
  apiGroup: {{ .apiGroup }}
  kind: {{ .kind }}
  name: {{ .name }}
{{- end -}}
{{- define "k8s-as-helm-lib.rolebinding.subjects.tpl" -}}
subjects:
  {{- range . }}
  - kind: {{ .kind }}
    name: {{ .name }}
    {{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
    {{- end }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
  {{- end }}
{{- end -}}
