apiVersion: {{ template "apiVersion" . }}
kind: RoleBinding
metadata:
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "rolebinding.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "rolebinding.name" . }}
{{ tpl ( include "k8s-as-helm-lib.rolebinding.roleref.tpl" .Values.roleRef) . }}
{{ tpl ( include "k8s-as-helm-lib.rolebinding.subjects.tpl" .Values.subjects) . }}
