apiVersion: {{ template "apiVersion" . }}
kind: RoleBinding
metadata:
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "rolebinding.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "rolebinding.name" . }}
roleRef:
  apiGroup: {{ .Values.roleRef.apiGroup }}
  kind: {{ .Values.roleRef.kind }}
  name: {{ .Values.roleRef.name }}
subjects:
  {{- range .Values.subjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
{{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
{{- end }}
{{- if .namespace }}
    namespace: {{ .namespace }}
{{- end }}
{{- end -}}
