kind: ReplicaSet
apiVersion: {{ template "apiVersion" . }}
metadata:
  name: {{ template "replicaset.name" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "replicaset.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
{{- if .Values.minReadySec }}
minReadySeconds: {{ .Values.minReadySec }}
{{- end }} 
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
     app: {{ template "pod.name" . }}
     chart: {{ .Chart.Name }}
     release: {{ .Release.Name }}
     heritage: {{ .Release.Service }}
  template:
   labels:
     app: {{ template "pod.name" . }}
     chart: {{ .Chart.Name }}
     release: {{ .Release.Name }}
     heritage: {{ .Release.Service }}
     {{- if .Values.labels }}
{{ toYaml .Values.pod.labels | indent 8 }}
{{- end }}
	{{ tpl ( include "k8s-as-helm-lib.pod.tpl" . ) . }}
