apiVersion: {{ template "apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "ingress.name" . }}
spec:
  {{- if and .Values.className (eq (include "apiVersion" .) "networking.k8s.io/v1") }}
  ingressClassName: {{ .Values.className }}
  {{- end }}
  rules:
  {{- range .Values.hosts }}
    - host: {{ .url }}
      {{ .protocol | default "http"}}:
        
{{- if .paths }}
        paths:
{{ toYaml .paths | indent 10 }}
{{- end }}
  {{- end -}}
{{- if .Values.tls }}
  tls:
{{ toYaml .Values.tls | indent 4 }}
{{- end -}}
