kind: Deployment
apiVersion: {{ template "apiVersion" . }}
metadata:
  name: {{ template "deployment.name" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "deployment.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:  
  replicas: {{ .Values.schedule | quote }}
  jobTemplate:
{{ tpl ( include "k8s-as-helm-lib.pod.tpl" . ) . | indent 4 }}
